// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Nap.Immutable")>]
[<assembly: AssemblyProductAttribute("Nap")>]
[<assembly: AssemblyDescriptionAttribute("A short and sweet REST client.")>]
[<assembly: AssemblyVersionAttribute("0.4.2")>]
[<assembly: AssemblyFileVersionAttribute("0.4.2")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] Version = "0.4.2"
    let [<Literal>] InformationalVersion = "0.4.2"
