// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Nap.Immutable.Html")]
[assembly: AssemblyProductAttribute("Nap")]
[assembly: AssemblyDescriptionAttribute("A short and sweet REST client.")]
[assembly: AssemblyVersionAttribute("0.4.2")]
[assembly: AssemblyFileVersionAttribute("0.4.2")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.4.2";
        internal const string InformationalVersion = "0.4.2";
    }
}
