// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Nap")]
[assembly: AssemblyProductAttribute("Nap")]
[assembly: AssemblyDescriptionAttribute("A short and sweet REST client.")]
[assembly: AssemblyVersionAttribute("0.4.0")]
[assembly: AssemblyFileVersionAttribute("0.4.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.4.0";
        internal const string InformationalVersion = "0.4.0";
    }
}
